# Generated by Django 5.2.4 on 2025-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
