# Generated by Django 5.2.4 on 2025-07-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookings_booking_time_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
