# Generated by Django 5.2.4 on 2025-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookings_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_time',
            field=models.DateField(auto_now=True),
        ),
    ]
